services:
  - type: web
    runtime: static
    name: parel-on
    buildCommand: npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
